#ifndef RENDER_ENUMERATIONS_H
#define RENDER_ENUMERATIONS_H

typedef enum R2DFUNC {
    FUNC_MANDELBROT,
    FUNC_MANDELBRIM,
    FUNC_FEATHERBOOT,
    FUNC_BURNINGSHIP,
} R2DFUNC;

typedef enum R2DSTOP {
    STOP_MANDELBROT,
    STOP_PAVILION,
    STOP_CRYSTALINE,
} R2DSTOP;

#endif // RENDER_ENUMERATIONS_H
